import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import { ReactNode } from "react";
import { Metadata } from 'next';

interface RootLayoutProps {
  children: ReactNode;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport = {
  themeColor: '#ffffff',
};

export const metadata: Metadata = {
  title: "Vibha Create Next App",
  description: "Generated by vibha next app",
  icons: {
    icon: [
    {
      url: "web-app-manifest-192x192.png",
      type: "image/png",
      sizes: "192x192"
    },
    {
      url: "web-app-manifest-512x512.png",
      type: "image/png",
      sizes: "512x512"
    }
  ],
  apple: 'web-app-manifest-192x192.png'
  }
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
    <head>
        <meta name="theme-color" content="#0f172a" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/web-app-manifest-192x192.png" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
